#!/bin/bash

# pip install paramiko zabbix_api httplib2

pip install -i http://160.85.4.29:8080/local -r $OPENSHIFT_REPO_DIR/req.deps

echo "Installing MCN SDK"
curl -k -o $OPENSHIFT_DATA_DIR/sdk.tar.gz 'https://owncloud.mobile-cloud-networking.eu/owncloud/public.php?service=files&t=01ad0519e7e4ad9bc8fdbf5f959f183e&download'
pip install $OPENSHIFT_DATA_DIR/sdk.tar.gz
